---
- name: Add DAMS_HOME to PATH
  lineinfile:
    path: "{{ damspas_home_dir }}/.bashrc"
    line: "export DAMS_HOME=/pub/dams"
    insertafter: EOF

- name: Clone damsrepo
  git:
    repo: https://github.com/ucsdlib/damsrepo.git
    dest: "{{ damspas_shared_dir }}/damsrepo"

- name: Build damsrepo
  command: bash -lc "cd {{ damspas_shared_dir }}/damsrepo && ant webapp"

- name: Create damsrepo config directories
  become: yes
  file:
    state: directory
    dest: '{{ item }}'
    owner: 'tomcat7'
    group: 'tomcat7'
  with_items:
    - '{{ damspas_damsrepo_home }}'
    - '{{ damspas_damsrepo_home }}/editBackups'
    - '{{ damspas_damsrepo_home }}/xsl'

- name: Install damsrepo config files
  become: yes
  copy:
    remote_src: yes
    src: "{{ damspas_shared_dir }}/damsrepo/src/{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "lib2/postgresql-9.2-1002.jdbc4.jar", dest: "/usr/share/tomcat7/lib/postgresql-9.2-1002.jdbc4.jar" }
    - { src: "properties/jhove.conf", dest: "{{ damspas_damsrepo_home }}/jhove.conf" }

- name: Install damsrepo policy and properties files
  become: yes
  copy:
    src: "files/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: 'tomcat7'
    group: 'tomcat7'
  with_items:
    - { src: "dams.properties", dest: "{{ damspas_damsrepo_home }}/dams.properties" }
    - { src: "99dams.policy", dest: "/etc/tomcat7/policy.d/99dams.policy" }

- name: Install damsrepo xsl files
  become: yes
  copy:
    src: "files/xsl/"
    dest: "{{ damspas_damsrepo_home }}/xsl/"
    owner: 'tomcat7'
    group: 'tomcat7'

- name: Install dams data load script
  template:
    src: templates/load-dams-data.j2
    dest: "{{ damspas_home_dir }}/load-dams-data.sh"
    mode: 0754

- name: Check if dams data already exists
  become: yes
  become_user: postgres
  command: psql -c "SELECT COUNT(*) FROM dams_triples" dams
  ignore_errors: yes
  register: dams_query_response

- name: Load dams database data
  command: bash -lc "{{ damspas_home_dir }}/load-dams-data.sh"
  environment:
    DAMS_HOME: '/pub/dams'
  when: dams_query_response.stdout == ""

- name: Install dams resource to tomcat server
  become: yes
  blockinfile:
    path: /var/lib/tomcat7/conf/server.xml
    state: present
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: '<GlobalNamingResources>'
    content: |
      <Environment name="dams/home" value="/pub/dams" type="java.lang.String"/>
      <Resource name="jdbc/dams" auth="Container" type="javax.sql.DataSource" username="dams" password="dams" driverClassName="org.postgresql.Driver" maxActive="10" maxIdle="3" url="jdbc:postgresql://localhost/dams" maxWait="5000" validationQuery="select 1" logAbandoned="true" testOnBorrow="true" removeAbandonedTimeout="60" removeAbandoned="true" testOnReturn="true"/>'

- name: Restart tomcat service
  become: yes
  service:
    name: tomcat7
    state: restarted

- name: Deploy damsrepo webapp
  become: yes
  become_user: tomcat7
  command: bash -lc "cd {{ damspas_shared_dir }}/damsrepo && ant -Ddeploy.home=/var/lib/tomcat7/webapps local-deploy"
