---
- name: Clone damspas
  git:
    repo: https://github.com/ucsdlib/damspas.git
    dest: "{{ damspas_shared_dir }}/damspas"
    version: 'develop'

- name: Bundle install
  bundler:
    state: present
    chdir: "{{ damspas_shared_dir }}/damspas"
    executable: /home/vagrant/.rbenv/shims/bundle

- name: Run database migrations
  shell: /home/vagrant/.rbenv/shims/bundle exec rake db:migrate RAILS_ENV={{ item }}
  args:
    chdir: "{{ damspas_shared_dir }}/damspas"
  with_items:
    - test
    - development

- name: Run damspas test suite (go get coffee)
  shell: /home/vagrant/.rbenv/shims/bundle exec rake spec
  args:
    chdir: "{{ damspas_shared_dir }}/damspas"

- name: Start unicorn webserver for damspas
  shell: /home/vagrant/.rbenv/shims/bundle exec unicorn -D -p 3000
  args:
    chdir: "{{ damspas_shared_dir }}/damspas"
