---
- name: Start postgresql service
  become: yes
  service:
    name: postgresql
    enabled: yes
    state: started

- name: Create dams database
  become: yes
  become_user: postgres
  postgresql_db:
    name: dams
    state: present

- name: Create dams database user
  become: yes
  become_user: postgres
  postgresql_user:
    db: dams
    name: dams
    password: dams
    priv: ALL
