---
- name: Start postgresql service
  become: yes
  service:
    name: postgresql
    enabled: yes
    state: started

- name: Create dams database
  become: yes
  postgresql_db:
    login_user: postgres
    name: dams
    owner: dams
    state: present

- name: Create dams database user
  become: yes
  postgresql_user:
    login_user: postgres
    db: dams
    name: dams
    password: dams
    priv: ALL
